### PR TITLE
Initial Draft for Monocular Depth Estimation

### PR DESCRIPTION
**Pull request by vaibhawkhemka**
### DepthEstimation Component

The component takes frames from the camera as input and predicts the depth of each pixel in the frame as output.

### DepthEstimationClient Component

The component uses _DepthEstimation_ and _camerasimple_ for building **DepthMap** using depth of the frames.

### CODE REVIEW

**Comment by vaibhawkhemka** [comment]
Please review this @DarkGeekMS

**Comment by DarkGeekMS** [comment]
PR of RoboComp interfaces related with this PR robocomp/robocomp#329

**Comment by DarkGeekMS** [comment]
Hello @vaibhawkhemka ,
I'm currently reviewing your PR and great work!
However, as I mentioned, I would like to know more about your plan and your elaboration for your current work.

**Comment by vaibhawkhemka** [comment]
Hello @DarkGeekMS,
I want to add on the work with further extensions/features for my Gsoc project and thought of a couple of ideas/features to implement them making it more robust and efficient.
Few ideas/Features are:
- **Increasing speed of the model to work even on low-processing devices like microprocessors** 
- **Object detection over depth estimation**
   The current Object detection algorithm detects objects who are both far and near the robot/camera. Thus, making it more 
   computationally expensive and less informative. So, only detecting nearby objects is more significant for any robot to tackle 
   any risk situation and it also leads to a decrease in computational cost.     
- **Segmentation using Depth estimation**
- **3D-Reconstruction  using Depth estimation**          

So, these are some of the ideas/plans. 
What are your thoughts on these ideas for implementation?

**Comment by DarkGeekMS** [comment]
@vaibhawkhemka 
The first point is somewhat essential for our project, that the component should work in real-time during inference on mid to low-end devices.
I have been thinking about the second point, as well, for collision detection.
The third and fourth point are slightly out of the project scope, but it will be nice to have, if we got the time.
You should think about adding the integration with DSR to your proposal, too.

**Comment by DarkGeekMS** [comment]
@vaibhawkhemka 
Regarding your PR,
You did a good job, but I have a couple of concerns :
1) You haven't mentioned what DNN architecture you used, I guess it's [DenseDepth](https://arxiv.org/abs/1812.11941) pretrained weights. But have you considered using a more recent approach? The project might involve some development of DNN model depending on your architecture of choice.
2) How are you planning to speed up such architecture or you are planning on using something else ?
If so, we should discuss this and you should mention it in your proposal.

**Comment by vaibhawkhemka** [comment]
@DarkGeekMS 
For the first point, I will update the README with DNN architecture used, which is correctly guessed by you i.e [DenseDepth](https://arxiv.org/pdf/1812.11941.pdf). And I have implemented/considered different approaches as well like-Adabins etc. And I found that most of these model is build on encoder-decoder which is increasing model complexity and thus decreasing speed while DenseDepth only use encoder-decoder. But still, trying to build a different approach and looking forward to the best model.

For the second point, different approaches to speed up architecture are:
- **Reducing the Model complexity**
   DenseDepth involves a very deep model which is resulting in reduced speed. Thus, reducing the model depth will increase the 
   speed of the model while not significantly decreasing the accuracy due to the trade-off between speed and accuracy.  
- **Pruning the Model**
   Removing all the redundant weights will significantly increase the speed. 
- **Other Approach**  
   The camera captures the scene which consists of stationary objects(many) and moving objects (few), which is most of the cases.
   Motivation for this idea is [here](https://www.cs.cornell.edu/~zl548/images/Learning_the_Depths_of_Moving_People_by_Watching_Frozen_People_TPAMI.pdf) 
   for estimating depth. The idea can be made generalizable for all objects not only for moving people with the appropriate 
   datasets.

And I will also add DSR integration to my proposal.
Thanks

What are your thoughts on these ideas?

**Comment by DarkGeekMS** [comment]
@vaibhawkhemka 
I have three points to tell here : 
1) I think reducing the model complexity will significantly hit the accuracy, as DenseDepth is already an old architecture and suffers from its own issues. However, pruning and quantization can be a good solution for such case.
2) You should consider light-weight architectures like [MiniNet](https://arxiv.org/abs/2006.15350) in your search and also, self-supervised / real-time architectures, if possible.
3) Regarding the last idea, as you said it's dependent on the dataset, but it's a good approach to go with. Again, considering self-supervised approaches can help in such cases.

**Comment by vaibhawkhemka** [comment]
@DarkGeekMS 
I read the paper MiniNet, it was a really interesting approach using recurrent approach and would be exciting/challenging to implement these. Thus,
Things to be included in the proposal as discussed are:

1. Two different methods for depth estimation in real-time:
    - Implementing **Supervised Learning** i.e Densedepth along with pruning and optimization for real-time estimation.
    - Implementing **Self-Supervised Learning** i.e use of light-weight architectures like MiniNet for real-time estimation.
2.  Integrating these with DSR.
3.  Collision Detection for nearby objects using depth, if time permits.

Any Suggestions?? or anything that needs to be modified or added??

**Comment by DarkGeekMS** [comment]
@vaibhawkhemka 
I think that's very good for the proposal, along with some elaboration of system architecture and the reasons behind your choices, as well as your project timeline.
Final point, you don't have to stick with DenseDepth and MiniNet, you can choose whatever DNN architecture you want given reasonable justification.

**Pull request merged**
